name: "Stage publish UI"

on:
    pull_request:
        branches:
            - feat/neo4j-graphql-ui
        paths-ignore:
            - "docs/**"

jobs:
    pack:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/setup-node@v3
            with:
            node-version: lts/*
            cache: yarn
        - name: Install dependencies
            run: yarn
        - name: Build UI
            run: yarn build
            working-directory: packages/graphql-ui
        - name: Publish documentation
            run: |
                npm install -g surge
                surge ./dist neo4j-graphql-ui-stage.surge.sh --token ${{ secrets.SURGE_TOKEN }}
            working-directory: packages/graphql-ui
