name: "Stage publish UI"

on:
    pull_request:
      branches:
        - dev
        - feat/neo4j-graphql-ui
      paths:
        - "packages/graphql-ui/**"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            package:
              - graphql-ui

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            node-version: lts/*
            cache: yarn
        - name: Install dependencies
          run: yarn
        - name: Build ${{ matrix.package }}
          run: yarn build
          working-directory: packages/${{ matrix.package }}

    publish-ui:
      needs:
        - build

      runs-on: ubuntu-latest

      steps:
      - uses: actions/setup-node@v3
      - name: Publish GraphQL UI to surge
        run: |
            npm install -g surge
            surge ./dist neo4j-graphql-ui-stage.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        working-directory: packages/graphql-ui