name: "UI Build"

on:
    workflow_dispatch:
    
    pull_request:
      branches:
        - dev
      paths:
        - "packages/graphql-ui/**"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: UI build
        run: |
          yarn
          yarn build
        working-directory: packages/graphql-ui
      - name: Archive UI
        uses: actions/upload-artifact@v2
        with:
          name: graphqlui
          path: packages/graphql-ui/dist
