name: "Build UI for stage env"

on:
    pull_request:
      branches:
        - dev
        - feat/neo4j-graphql-ui
      paths:
        - "packages/graphql-ui/**"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Build UI
        run: |
          yarn
          yarn build
        working-directory: packages/graphql-ui
      - name: Archive UI
        uses: actions/upload-artifact@v2
        with:
          name: ui
          path: packages/graphql-ui/dist
